export const ADD_FOOD = "ADD_FOOD";
export const REMOVE_FOOD = "REMOVE_FOOD";

export const SET_FOODS = "SET_FOODS";
export const FETCH_FOODS_ERROR = "FETCH_FOODS_ERROR";

export const PURCHASING_FOOD_START = "PURCHASING_FOOD_START";
export const PURCHASE_FOOD_SUCCESS = "PURCHASE_FOOD_SUCCESS";
export const PURCHASE_FOOD_FAIL = "PURCHASE_FOOD_FAIL";
export const PURCHASE_SUCCESS_MESSAGE = "PURCHASE_SUCCESS_MESSAGE";

export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";
